<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Lecturer;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class LecturerSeeder extends Seeder
{
    public function run(): void
    {
        // Create admin user first if not exists
        $adminUser = User::where('email', 'admin@jadwal-app.com')->first();

        if (!$adminUser) {
            $adminUser = User::create([
                'name' => 'Administrator',
                'email' => 'admin@jadwal-app.com',
                'password' => Hash::make('password'),
                'role' => 'admin',
                'email_verified_at' => now(),
            ]);
        }

        // Sample lecturer data
        $lecturers = [
            [
                'employee_number' => '198001001',
                'name' => 'Dr. Ahmad Pratama, S.T., M.T.',
                'email' => 'ahmad.p@university.ac.id',
                'phone' => '+62 812-3456-0001',
                'gender' => 'male',
                'birth_date' => '1980-01-15',
                'birth_place' => 'Jakarta',
                'address' => 'Jl. Merdeka No. 123, Jakarta Pusat',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'postal_code' => '10110',
                'nationality' => 'Indonesia',
                'religion' => 'Islam',
                'blood_type' => 'A',
                'id_card_number' => '3171011501800001',
                'status' => 'active',
                'employment_type' => 'permanent',
                'employment_status' => 'Active',
                'hire_date' => '2005-08-01',
                'position' => 'Lecturer',
                'rank' => 'Profesor',
                'department' => 'Teknik Informatika',
                'faculty' => 'Sekolah Pascasarjana',
                'highest_education' => 'S3',
                'education_institution' => 'Institut Teknologi Bandung',
                'education_major' => 'Teknik Informatika',
                'graduation_year' => '2008',
                'specialization' => 'Artificial Intelligence, Machine Learning',
                'academic_load' => 12,
                'office_room' => 'Lab Komputer 301',
                'is_active' => true,
                'created_by' => $adminUser->id,
            ],
            [
                'employee_number' => '198001002',
                'name' => 'Dr. Siti Nurhaliza, S.Pd., M.Pd.',
                'email' => 'siti.n@university.ac.id',
                'phone' => '+62 812-3456-0002',
                'gender' => 'female',
                'birth_date' => '1982-05-20',
                'birth_place' => 'Bandung',
                'address' => 'Jl. Sudirman No. 456, Bandung',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'postal_code' => '40111',
                'nationality' => 'Indonesia',
                'religion' => 'Islam',
                'blood_type' => 'O',
                'id_card_number' => '3272052005820002',
                'status' => 'active',
                'employment_type' => 'permanent',
                'employment_status' => 'Active',
                'hire_date' => '2008-06-15',
                'position' => 'Lecturer',
                'rank' => 'Lektor Kepala',
                'department' => 'Sistem Informasi',
                'faculty' => 'Sekolah Pascasarjana',
                'highest_education' => 'S3',
                'education_institution' => 'Universitas Indonesia',
                'education_major' => 'Ilmu Komputer',
                'graduation_year' => '2015',
                'specialization' => 'Database Systems, Software Engineering',
                'academic_load' => 10,
                'office_room' => 'Lab Sistem 201',
                'is_active' => true,
                'created_by' => $adminUser->id,
            ],
            [
                'employee_number' => '198001003',
                'name' => 'Bambang Santoso, S.Kom., M.Kom.',
                'email' => 'bambang.s@university.ac.id',
                'phone' => '+62 812-3456-0003',
                'gender' => 'male',
                'birth_date' => '1985-09-10',
                'birth_place' => 'Surabaya',
                'address' => 'Jl. Ahmad Yani No. 789, Surabaya',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60231',
                'nationality' => 'Indonesia',
                'religion' => 'Islam',
                'blood_type' => 'B',
                'id_card_number' => '3575091009850003',
                'status' => 'active',
                'employment_type' => 'permanent',
                'employment_status' => 'Active',
                'hire_date' => '2010-03-01',
                'position' => 'Lecturer',
                'rank' => 'Lektor',
                'department' => 'Teknik Elektro',
                'faculty' => 'Sekolah Pascasarjana',
                'highest_education' => 'S2',
                'education_institution' => 'ITS',
                'education_major' => 'Teknik Elektro',
                'graduation_year' => '2012',
                'specialization' => 'Internet of Things, Embedded Systems',
                'academic_load' => 8,
                'office_room' => 'Lab Elektronika 103',
                'is_active' => true,
                'created_by' => $adminUser->id,
            ],
            [
                'employee_number' => '198001004',
                'name' => 'Dewi Lestari, S.E., M.T.',
                'email' => 'dewi.l@university.ac.id',
                'phone' => '+62 812-3456-0004',
                'gender' => 'female',
                'birth_date' => '1988-03-25',
                'birth_place' => 'Yogyakarta',
                'address' => 'Jl. Malioboro No. 234, Yogyakarta',
                'city' => 'Yogyakarta',
                'province' => 'DI Yogyakarta',
                'postal_code' => '55161',
                'nationality' => 'Indonesia',
                'religion' => 'Islam',
                'blood_type' => 'AB',
                'id_card_number' => '3471032503880004',
                'status' => 'on_leave',
                'employment_type' => 'permanent',
                'employment_status' => 'On Leave',
                'hire_date' => '2012-09-01',
                'position' => 'Lecturer',
                'rank' => 'Lektor',
                'department' => 'Manajemen',
                'faculty' => 'Sekolah Pascasarjana',
                'highest_education' => 'S2',
                'education_institution' => 'UGM',
                'education_major' => 'Manajemen',
                'graduation_year' => '2018',
                'specialization' => 'Strategic Management, Business Analytics',
                'academic_load' => 0,
                'office_room' => 'Ruang Dosen MM 105',
                'is_active' => true,
                'created_by' => $adminUser->id,
            ],
            [
                'employee_number' => '198001005',
                'name' => 'Robert Johnson, Ph.D.',
                'email' => 'robert.j@university.ac.id',
                'phone' => '+62 812-3456-0005',
                'gender' => 'male',
                'birth_date' => '1979-07-08',
                'birth_place' => 'New York',
                'address' => 'Jl. Diponegoro No. 567, Semarang',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'postal_code' => '50231',
                'nationality' => 'Indonesia',
                'religion' => 'Christian',
                'blood_type' => 'O+',
                'id_card_number' => '3375070803790005',
                'status' => 'active',
                'employment_type' => 'guest',
                'employment_status' => 'Visiting Professor',
                'hire_date' => '2015-01-15',
                'position' => 'Visiting Professor',
                'rank' => 'Profesor',
                'department' => 'Teknik Sipil',
                'faculty' => 'Sekolah Pascasarjana',
                'highest_education' => 'S3',
                'education_institution' => 'MIT',
                'education_major' => 'Civil Engineering',
                'graduation_year' => '2010',
                'specialization' => 'Structural Engineering, Earthquake Engineering',
                'academic_load' => 6,
                'office_room' => 'Lab Sipil 201',
                'is_active' => true,
                'created_by' => $adminUser->id,
            ],
        ];

        // Insert lecturers
        foreach ($lecturers as $lecturerData) {
            Lecturer::create($lecturerData);
        }

        echo "Created " . count($lecturers) . " sample lecturers\n";
    }
}